# Generated by Django 5.2.7 on 2025-10-18 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emaillog_tracking_pixel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MailCurrent.io', max_length=100)),
                ('site_description', models.TextField(default='Email API Service Status')),
                ('show_uptime', models.BooleanField(default=True)),
                ('show_metrics', models.BooleanField(default=True)),
                ('show_incidents', models.BooleanField(default=True)),
                ('auto_refresh_seconds', models.PositiveIntegerField(default=60)),
                ('contact_email', models.EmailField(default='status@mailcurrent.io', max_length=254)),
                ('twitter_handle', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded Performance'), ('partial', 'Partial Outage'), ('major', 'Major Outage'), ('maintenance', 'Maintenance')], max_length=20)),
                ('response_time', models.PositiveIntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('uptime_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('message', models.TextField(blank=True, help_text='Status message for users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='api.systemcomponent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved'), ('scheduled', 'Scheduled Maintenance')], max_length=20)),
                ('impact', models.CharField(choices=[('none', 'No Impact'), ('minor', 'Minor Impact'), ('major', 'Major Impact'), ('critical', 'Critical Impact')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_components', models.ManyToManyField(blank=True, to='api.systemcomponent')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('uptime_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_response_time', models.PositiveIntegerField(help_text='Average response time in milliseconds')),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('api_requests', models.PositiveIntegerField(default=0)),
                ('error_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
