# Generated by Django 5.2.7 on 2025-10-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_statuspagesettings_systemcomponent_componentstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='custom_smtp_host',
            field=models.CharField(blank=True, help_text='Custom SMTP host', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='custom_smtp_password',
            field=models.CharField(blank=True, help_text='Custom SMTP password', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='custom_smtp_port',
            field=models.PositiveIntegerField(default=587, help_text='Custom SMTP port'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='custom_smtp_use_ssl',
            field=models.BooleanField(default=False, help_text='Use SSL for custom SMTP'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='custom_smtp_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS for custom SMTP'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='custom_smtp_username',
            field=models.CharField(blank=True, help_text='Custom SMTP username', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statuspagesettings',
            name='site_description',
            field=models.TextField(default='MailCurrent.io Service Status'),
        ),
    ]
