# Generated by Django 5.2.7 on 2025-10-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apikey_custom_smtp_host_apikey_custom_smtp_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='custom_smtp_password',
            field=models.CharField(blank=True, help_text='Custom SMTP password (encrypted)', max_length=500, null=True),
        ),
    ]
