# Generated by Django 5.2.7 on 2025-10-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailverificationtoken_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user account is active. Unselect this instead of deleting accounts.'),
        ),
    ]
